name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ghcr.io/${{ github.repository }}/collector
          ghcr.io/${{ github.repository }}/processor
          ghcr.io/${{ github.repository }}/trainer
          ghcr.io/${{ github.repository }}/detector
          ghcr.io/${{ github.repository }}/api
          ghcr.io/${{ github.repository }}/dashboard
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,format=long
          type=ref,event=branch
    
    - name: Build and push Collector image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: deployment/docker/collector.Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/collector:${{ steps.meta.outputs.version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build and push Processor image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: deployment/docker/processor.Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/processor:${{ steps.meta.outputs.version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build and push Trainer image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: deployment/docker/trainer.Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/trainer:${{ steps.meta.outputs.version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build and push Detector image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: deployment/docker/detector.Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/detector:${{ steps.meta.outputs.version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build and push API image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: deployment/docker/api.Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/api:${{ steps.meta.outputs.version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build and push Dashboard image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: deployment/docker/dashboard.Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/dashboard:${{ steps.meta.outputs.version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max